name: Build and Publish Catalog

on:
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: write   # to push dist/

jobs:
  build-sign-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build catalog-signer
        run: cargo build -p catalog-signer --release

      - name: Generate catalog
        env:
          CATALOG_PRIVKEY: ${{ secrets.CATALOG_PRIVKEY }}
        run: |
          mkdir -p dist
          ./target/release/catalog-signer sign \
            --decoys templates/decoys.yml \
            --meta templates/catalog.meta.yml \
            --out dist/catalog.json \
            --sig dist/catalog.json.sig

      - name: Verify signature
        run: |
          ./target/release/catalog-signer verify \
            --catalog dist/catalog.json \
            --sig dist/catalog.json.sig \
            --pubkey-file keys/publisher.pub

      - name: Commit dist artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update dist catalog artifacts'
          file_pattern: dist/**

      # Optional: publish GitHub Pages
      # - name: Upload Pages artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: dist
      # - name: Deploy to GitHub Pages
      #   uses: actions/deploy-pages@v4
